module.exports = {
  authAccesstoken: require('./tokenRequest/authAccesstoken'),
  authRefreshtoken: require('./tokenRequest/authRefreshtoken'),
  signup: require('./users/signup'),
  withdrawal: require('./users/withdrawal'),
  login: require('./users/login'),
  logout: require('./users/logout'),
  edit: require('./users/edit'),
  myPage: require('./myPage'), 
  cool: require('./cool'),
  main: require('./main'),
  writeComment: require('./comments/writeComment'),
  deleteComment: require('./comments/deleteComment'), 
  clickPost: require('./posts&hashtags/clickPost'),
  updatePost: require('./posts&hashtags/updatePost'),
  writePost: require('./posts&hashtags/writePost'),
  deletePost: require('./posts&hashtags/deletePost'),
  };